### ISSUE TITLE
An error occurred while saving data: Cannot save file into a non-existent directory: 'output\m'

### ISSUE THREAD

**Issue by vivek-patel-NF** [r7avi/Google-Maps-Data-Scrapper#3]
ive just changed total = 1 and it is giving me error

```
An error occurred while saving data: Cannot save file into a non-existent directory: 'output\m'
```

**Comment by r7avi** [comment]
Let me check

**Comment by r7avi** [comment]
i just checked and i can confirmed that script working perfectly without any issues.

install these : 

Install Python 3.10 Version 
and 
Upgrade Pip : python -m pip install --upgrade pip
Install Requirements : pip install playwright pandas openpyxl tqdm playwright install

and run script by Python : Python run.py
(add your search queries to Query.txt (each line 1 query ) and set number of results need in run.py (min 2 to max 150)

**Comment by r7avi** [comment]
or just create /output directory manually

**Comment by vivek-patel-NF** [comment]
I've created manually, but still try this query
in any mode
```
PS C:\Users\BSH\OneDrive\Documents\GitHub\Google-Maps-Data-Scrapper> python .\run.py
Would you like to input search term manually (1) or use Query.txt (2)? 1
Please enter your search term: smart driver maharashtra in 411061
------ smart driver maharashtra in 411061 ------
Scraping took 0.71 minutes.
PS C:\Users\BSH\OneDrive\Documents\GitHub\Google-Maps-Data-Scrapper> 
```
 total is set to 2

**Comment by r7avi** [comment]
try to load query in Query.txt

**Comment by r7avi** [comment]
did it found data on that run?

like this :

Found: 8
Scrolled to: 8
Clicked on: 5
Scrolled to: 16
Scrolled to: 20
Scrolled to: 24
Scrolled to: 24
You've reached the end of the search query.

try to set total = 5 (atleast 5)

**Comment by vivek-patel-NF** [comment]
But ig issue is My search query is too exact. that it is only opening one place not list of places, it is not showing other places list that's the issue

ig when i run code it is directly opening one place :- 

![image](https://github.com/user-attachments/assets/54662f30-08c7-4525-a0a8-951a5fcd682d)

**Comment by r7avi** [comment]
oh!

yes! if it found one , then it doesn't fetch data. it ignores.

because script is designed to fetch all links and then open 1 by 1 to scrape data

**Comment by vivek-patel-NF** [comment]
can you please suggest me changes?

I'll send a Pr if I can contribute some time to this project

**Comment by r7avi** [comment]
> can you please suggest me changes?
> 
> I'll send a Pr if I can contribute some time to this project

okay!

**Comment by r7avi** [comment]
if you can explain me your purpose of using this script, like trying to scrape data from specific niche , then i can help you out,
because lot of keywords gets multiple results , so script can scrape all data at once,

and yeah i can modify script to handle single search results .

**Comment by vivek-patel-NF** [comment]
my search queries txt is similar to this
:- 
```
chimanlal vadilal & company maharashtra in 400003
horizon designers maharashtra in 411030
shree shruti infraproducts & services private limited maharashtra in 402107

```

however some queries in my Query.txt are returning multiple results in that case I want first N restults!

also i want theres a section for websites down in any maps place. 
![image](https://github.com/user-attachments/assets/0df74d89-1160-40af-9e6b-136021057d2f)


your repo is charm!

Thanks!

**Comment by r7avi** [comment]
chimanlal vadilal & company in 400003
horizon designers in 411030
shree shruti infraproducts & services private limited in 402107

remove maharashtra, as you are already entering pincode

For first N results , modify run.py total to 2 or 1 , so it will get first 1 or 2 results of that query

section for websites : i can modify script to catch website links, 
and then you can use my website email scrapper repo to scrape the emails - https://github.com/r7avi/Scrape-Emails-from-Websites
